name: dino_run
description: A 2D infinite side scroller.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: 1.16.0
  flame_audio: 2.10.0
  hive: 2.2.3
  path_provider: 2.1.2
  provider: 6.1.1
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6

dev_dependencies:
  hive_generator: 2.0.1
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/parallax/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/audio/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
